---
title: "t-sne"
author: "adrian"
date: "12/3/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(Rtsne)
library(openxlsx)
library(class)
library(reticulate)
```



```{r cars}
if(file.exists('data/tsne-df.rds')) {
  df <- readRDS('data/tsne-df.rds')
} else {
  raw_data <- readRDS('features/intSites_full_ALL_CLL_plus_epi.rds')
  unlearn_features<- colnames(raw_data)[1:29]
  full_data <- raw_data %>% drop_na() %>% distinct(across(-all_of(unlearn_features)),.keep_all = TRUE)
  full_data_x <- full_data %>% select(-all_of(unlearn_features))
  full_data_y <- full_data %>% select(all_of(unlearn_features))
  t_sne <- Rtsne(full_data_x,check_duplicates=FALSE,verbose=TRUE,num_threads=30)

  df_tmp <- data.frame(
    X=t_sne$Y[,1],
    Y=t_sne$Y[,2]
  )

  df_tmp2 <- cbind(df_tmp,full_data_y) 
  response_class <- read.xlsx('data/ALL_CLL_samples_20211124.xlsx','All_samples') %>%
    select(c('Patient','Response_class')) %>% rename(patient=Patient)
  df <- left_join(df_tmp2,response_class,by='patient')  %>%
    drop_na() %>%
    filter(Response_class!='MISSING')
  saveRDS(df,file = 'data/tsne-df.rds')
}

#
#
```



```{r pressure, echo=FALSE}
ggplot(df, aes(x=X, y=Y, color=Response_class)) +
  geom_point() +
  facet_wrap( ~ Response_class)

pyx <- df %>% select(c(X,Y))
pyy <- df %>% select(Response_class)
```

```{python conda}
import pandas
# evaluate an radius neighbors classifier model on the dataset
from numpy import mean
from numpy import std
from sklearn.datasets import make_classification
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import MinMaxScaler
from sklearn.neighbors import RadiusNeighborsClassifier
# define dataset
X, y = make_classification(n_samples=1000, n_features=20, n_informative=15, n_redundant=5, random_state=1)
# define model
model = RadiusNeighborsClassifier()
# create pipeline
pipeline = Pipeline(steps=[('norm', MinMaxScaler()),('model',model)])
# define model evaluation method
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
# evaluate model
scores = cross_val_score(pipeline, X, y, scoring='accuracy', cv=cv, n_jobs=-1)
# summarize result
print('Mean Accuracy: %.3f (%.3f)' % (mean(scores), std(scores)))

model = RadiusNeighborsClassifier(radius=0.1)
model.fit(r.pyx,r.pyy.values.ravel())

yhat = model.predict(r.pyx)


```

```{r yhats}
#sum(py$yhat == df$Response_class)
df_imp1 <- df[py$yhat == df$Response_class,]
 ggplot(df_imp1, aes(x=X, y=Y,color=Response_class)) +
 geom_point() +
 facet_wrap( ~ Response_class)
```